language: ruby
sudo: false
rvm:
  - 2.2.3
before_install:
  - printenv
  - cd example && BUNDLE_GEMFILE="Gemfile" bundle install && cd ..
env:
  - RAILS_VERSION=3.1.0
  - RAILS_VERSION=4.0.0
  - RAILS_VERSION=4.2.0
  - RAILS_VERSION=5.0.0.beta2
